version: "3"

services:
  media:
    build: media/
    command: uvicorn server:app --host 0.0.0.0 --port 8081
    ports:
      - "8080:8081"
    depends_on:
      - s3
      - db
    env_file:
      - minio.env
  server:
    build: server/
    command: uvicorn server:app --host 0.0.0.0 --port 8080
    ports:
      - "80:8080"
    depends_on:
      - media
      - s3
      - db
  db:
    image: postgres:latest
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=postgres_db
      - PGDATA=/var/lib/postgresql/data/pgdata

  s3:
    image: minio/minio:latest
    command: minio server /data --console-address :9001
    expose:
      - 9000
      - 9001
    env_file:
      - minio.env
volumes:
  pgdata: